baseurl = "http://example.org/"
title = "IPLD"
tagline = "InterPlanetary Linked Data"
author = "Protocol Labs"
languageCode = "en-us"
theme = "default"

copyright = "IPLD - All rights reserved."

[params]
  logo      = "/images/logo.jpg"
  twitter   = "https://twitter.com/rakuishi07"
  facebook  = "https://www.facebook.com/ochiishikoichiro"
  github    = "https://github.com/rakuishi/"
  email     = "rakuishi@gmail.com"
  analytics = "UA-12345678-9"

	# Themes main color, will be applied in many places
	main_color = "#000"

	links = [{
		name = "Github",
		link = "ARtrib"
	}]

	navigation = [{
		name = "Home",
		link = "../"
	}, {
		name = "Implementations",
		link = "../implementations"
	}]
		
	[navigation]
		[navigation.home]

		[navigation.implementations]

		[navigation.examples]
		name = "Examples"
		link = "../examples"

	[features]
		[features.integrity]
		name = "Cryptographic Integrity Checking"
		icon = "random_icon.png"
		summary = "Somewhat cool feature yeah"

		[features.immutable]
		name = "Immutable Datastructures"
		icon = "another_random_icon.png"
		summary = "Even cooler feature!"

	[supported_langs]
		[supported_langs.js]
		name = "JavaScript"
		icon = "icons/javascript.png"
		link = "github.com/ipld/js-ipld"

		[supported_langs.go]
		name = "Go"
		icon = "icons/go.png"
		link = "github.com/ipld/go-ipld"

		[supported_langs.c]
		name = "C"
		icon = "icons/c.png"
		link = "github.com/ipld/c-ipld"

		[supported_langs.python]
		name = "Python"
		icon = "icons/python.png"
		link = "github.com/ipld/python-ipld"

	[talks]
		[talks.first]
		name = "Someone talking somewhere"
		video = "youtube.com/RandomVideo"

		[talks.second]
		name = "Someone talking somewhere else"
		video = "youtube.com/AnotherRandomVideo"
