baseurl: "http://example.org/"

title: "IPLD"
author: "Protocol Labs"
languageCode: "en-us"
theme: "default"
pygmentsstyle: "autumn"

copyright: "IPLD - All rights reserved."

params:
  main_color: "#ff4088"
  links:
    - name: "Github"
      link: "https://github.com/ipld/ipld"
    - name: "Specification"
      link: "https://github.com/ipld/specs"
  navigation:
    - name: "Home"
      link: "/"
    - name: "Getting Started"
      link: "getting-started"
  features:
    - name: "Integrity"
      icon: "social.svg"
      description: |
        URLs give no guarantees that the data we receive
        hasn't been compromised. The IPLD naming system
        ensures that no one can lie about the data they
        are serving.

    - name: "Distributed"
      icon: "cloud-data-distribution-symbol.svg"
      description: |
        Only the owner of a domain name can serve you
        the data behind a URL. In IPLD any computer
        that has the data can help and participate
        in distributing it

    - name: "Immutability"
      icon: "social.svg"
      description: |
        The content behind URLs can change or disappear,
        making our links broken or not pointing anymore
        to what we were expecting. IPLD links cannot mutate
  languages:
    - name: JavaScript
      icon: "javascript.svg"
      repo: "ipld/js-ipld-dag-cbor"
    - name: Go
      icon: "go.svg"
      repo: "ipfs/go-ipld"
    - name: C
      icon: "c.svg"
      status: "missing"
    - name: Python
      status: "missing"
      icon: "python.svg"

  #[params]
  #	links = [{
  #		name = "Github",
  #		link = "ARtrib"
  #	}]
  #
  #	navigation = [{
  #		name = "Home",
  #		link = "../"
  #	}, {
  #		name = "Implementations",
  #		link = "../implementations"
  #	}]
  #		
  #	[navigation]
  #		[navigation.home]
  #
  #		[navigation.implementations]
  #
  #		[navigation.examples]
  #		name = "Examples"
  #		link = "../examples"
  #
  #	[features]
  #		[features.integrity]
  #		name = "Cryptographic Integrity Checking"
  #		icon = "random_icon.png"
  #		summary = "Somewhat cool feature yeah"
  #
  #		[features.immutable]
  #		name = "Immutable Datastructures"
  #		icon = "another_random_icon.png"
  #		summary = "Even cooler feature!"
  #
  #	[supported_langs]
  #		[supported_langs.js]
  #		name = "JavaScript"
  #		icon = "icons/javascript.png"
  #		link = "github.com/ipld/js-ipld"
  #
  #		[supported_langs.go]
  #		name = "Go"
  #		icon = "icons/go.png"
  #		link = "github.com/ipld/go-ipld"
  #
  #		[supported_langs.c]
  #		name = "C"
  #		icon = "icons/c.png"
  #		link = "github.com/ipld/c-ipld"
  #
  #		[supported_langs.python]
  #		name = "Python"
  #		icon = "icons/python.png"
  #		link = "github.com/ipld/python-ipld"
  #
  #	[talks]
  #		[talks.first]
  #		name = "Someone talking somewhere"
  #		video = "youtube.com/RandomVideo"
  #
  #		[talks.second]
  #		name = "Someone talking somewhere else"
  #		video = "youtube.com/AnotherRandomVideo"
