baseurl: "http://example.org/"

title: "IPLD"
author: "Protocol Labs"
languageCode: "en-us"
theme: "ipld"
pygmentsstyle: "autumn"

copyright: "IPLD - All rights reserved."

params:
  main_color: "#ff4088"
  navigation:
    - name: "Home"
      link: "/"
      target: "internal"
    - name: "Tutorial"
      link: "tutorial"
      target: "internal"
    - name: "Github"
      link: "https://github.com/ipld/ipld"
      target: "external"
    - name: "Specification"
      link: "https://github.com/ipld/specs"
      target: "external"
  features:
    - name: "Secure Linking"
      icon: "social.svg"
      description: |
        URLs give no guarantees that the data we receive
        hasn't been compromised. The IPLD naming system
        ensures that no one can lie about the data they
        are serving.

    - name: "Distributed Naming"
      icon: "cloud-data-distribution-symbol.svg"
      description: |
        A domain’s owner is the only one who can serve you content.
        With IPLD, anyone who has the data helps with distributing
        it, too.

    - name: "Immutable Content"
      icon: "social.svg"
      description: |
        The content behind URLs can change or disappear,
        making our links broken or not pointing anymore
        to what we were expecting. IPLD links cannot mutate
  languages:
    - name: JavaScript
      icon: "javascript.svg"
      link: "ipld/js-ipld-dag-cbor"
    - name: Go
      icon: "go.svg"
      link: "ipfs/go-ipld"
    - name: C
      icon: "c.svg"
      status: "in-progress"
      link: "kenCode-de/c-ipld"
    - name: Others
      status: "missing"
      icon: "question-mark.svg"
      link: "ipld/ipld/issues/9"
